version: '3.8'

services:
    db:
        image: postgres:15
        container_name: notes-manager-db
        restart: unless-stopped
        ports:
            - '5436:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: n0t3sMaNaG3R
            POSTGRES_DB: postgres
        volumes:
            - notes-manager-db-data:/var/lib/postgresql/data

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: notes-manager-backend
        depends_on:
            - db
        ports:
            - '8000:8000'
        environment:
            DB_HOST: db
            DB_PORT: '5432'
            DB_USERNAME: postgres
            DB_PASSWORD: n0t3sMaNaG3R
            DB_NAME: postgres
            DB_SSLMODE: disable
            JWT_SECRET: supersecret

    frontend:
        image: node:18-alpine
        build:
            context: ./frontend/frontend
            dockerfile: Dockerfile
        container_name: notes-manager-frontend
        depends_on:
            - backend
        ports:
            - '5173:5173'
        environment:
            VITE_API_BASE_URL: http://backend:8000
            CHOKIDAR_USEPOLLING: "true"
            CHOKIDAR_INTERVAL: "300"
        volumes:
            - ./frontend/frontend:/app:delegated
            - /app/node_modules    
        working_dir: /app
        command: ['npm', 'run', 'dev', '--', '--host', '0.0.0.0', '--port', '5173']

volumes:
    notes-manager-db-data:
